### ISSUE TITLE
"no-empty-body" rule is broken

### ISSUE THREAD

**Issue by hugoduraes** [onechiporenko/eslint-plugin-mocha-cleanup#19]
I've found an issue with `no-empty-body` rule:

```js
it('test', () => expect('a').to.equal('a'));
```

The rule complains about an empty body, when it isn't, as you can see on the provided example.

**Comment by onechiporenko** [comment]
Hello, @hugoduraes. Issue is fixed in `v1.9.1` (already published).

**Comment by hugoduraes** [comment]
Wow, that was fast! Thanks 👍
