### ISSUE TITLE
Feature: detect variable assignment outside tests

### ISSUE THREAD

**Issue by jasonkarns** [onechiporenko/eslint-plugin-mocha-cleanup#2]
Doing variable assignment directly within `describe`/`context` callbacks (outside of `it` callbacks) makes said variables accessible to the tests through closures. As such, the variables create test pollution as the variables are shared between tests. Generally, the solution to this is to assign these variables to the context object that mocha creates for each test (which is bound as `this` within `beforeEach`/`it`/`afterEach` callbacks). However, ensuring that the variables are only _declared_ within the `describe` callbacks and that they are assigned within `beforeEach`/`it` callbacks is usually sufficient. (usually)

I propose a rule that finds any variables that are *assigned* within `describe`/`context` callbacks. I intend to work on a PR for this feature. Indeed, I was planning on creating an eslint plugin specifically for this rule, but figured that it would be quite at home in this plugin instead.

**Comment by onechiporenko** [comment]
Hi, @jasonkarns. It will very useful rule.
Looking forward fot PR. Thanks!

**Comment by onechiporenko** [comment]
@jasonkarns, am I right:
```javascript
var someGlob = require(''); // valid
describe('my cool suite', function () {

  var abc = 1234; // invalid

  beforeEach(function () {
      var b = 124; // valid
      this.a = b; // valid
  });

  it ('my cool test', function () {
      var a = 123; // valid
  });

});
```

**Comment by jasonkarns** [comment]
Yeah, that's what I was intending. Ideally one would minimize the amount of variables set at the very top-level as well (limiting them to `require`s only), but I don't think that would be relevant for this rule.

**Comment by jasonkarns** [comment]
Awesome, thanks!
