### ISSUE TITLE
Add recommended config

### ISSUE THREAD

**Issue by brettz9** [onechiporenko/eslint-plugin-mocha-cleanup#8]
Hi,

It'd be nice to avoid needing to add to `plugins` and manually adding best practice rules (instead just needing to add `extends: ['plugin:mocha-cleanup/recommended']` and enabling/overriding any additional rules desired). Would you be open to a recommended config?

I wouldn't think it should have specific assert limits or complexity limits by default as I'd think these would vary more by project, but some rules like `no-empty-title`, just seem good to get by default.

I could offer a PR if this were desired. Thanks!

**Comment by onechiporenko** [comment]
Hello, @brettz9. Thanks for idea!
PR is welcome :)
